/**
 * Temario oficial de Línea Aérea (convocatoria Aeroméxico Connect): las
 * SECCIONES de cada capítulo de cada fuente, tal como vienen en el documento
 * "Línea Aérea — TEMARIO CONNECT".
 *
 * Los capítulos (número, título y conteo) viven en `linea-aerea-meta.ts`, que
 * es el módulo ligero que cargan las pantallas de alumnas. Este archivo solo lo
 * importan el panel admin (para catalogar un reactivo en su capítulo y sección)
 * y los scripts de verificación del banco: por eso va aparte.
 *
 * Regla del banco: el campo `seccion` de un reactivo de Línea Aérea debe ser
 * uno de los textos de aquí para su `fuente` + `capitulo`. Se conserva el
 * idioma del temario (inglés para ATP/PHAK/Jeppesen, español para Legislación).
 */

/** Secciones por fuente → capítulo. Un capítulo sin entrada no tiene secciones. */
export const TEMARIO_SECCIONES: Record<string, Record<number, readonly string[]>> = {
  /* ─── ATP — Airline Transport Pilot Test Prep (ASA) ──────────── */
  ATP: {
    1: [
      "Applicable Regulations",
      "The ATP Certificate",
      "Flight Engineer Requirements",
      "Flight Attendants",
      "Experience and Training Requirements",
      "Part 135 Flight Crew Requirements",
      "Flight Crew Duty Time Limits",
      "Flight Duty Periods",
      "Dispatching and Flight Release",
      "Fuel Requirements",
      "Carriage of Passengers and Cargo",
      "Part 135 Carriage of Passengers and Cargo Requirements",
      "Emergency Equipment and Operations",
      "Part 135 Oxygen Requirements",
      "National Transportation Safety Board (NTSB)",
      "Part 135 Regulations",
      "Helicopter Regulations",
    ],
    2: [
      "Inoperative Equipment",
      "Pitot-Static Instruments",
      "Electronic Flight Instruments",
      "Safety of Flight Equipment",
      "Communications",
      "Navigation Equipment",
      "Horizontal Situation Indicator (HSI)",
      "Global Navigation",
      "Approach Systems",
      "GPS",
      "Airport Lighting and Marking",
      "Approach Lighting",
    ],
    3: [
      "Lift and Drag",
      "Critical Engine and VMC",
      "Maneuvering Flight",
      "Stability",
      "High Speed Flight",
      "Primary Flight Controls",
      "Tabs",
      "High-Lift Devices",
      "Helicopter Aerodynamics",
    ],
    6: [
      "Airspace",
      "NOTAMs (Notices To AirMen)",
      "Items on the Flight Plan",
      "Alternate Airport Planning",
      "ATC Clearances",
      "Takeoff Procedures",
      "Instrument Approaches",
      "Landing",
      "Communications",
      "Speed Adjustments",
      "Holding",
      "Charts",
    ],
    7: ["Flight Emergencies and Hazards", "Flight Physiology"],
    8: [
      "The Atmosphere",
      "Weather Systems",
      "Stability and Instability of Air",
      "Fog and Rain",
      "Thunderstorms",
      "Wind Shear",
      "Frost and Ice",
      "Icing",
      "Hazards of Structural Icing",
      "Frost Formation",
      "Turbulence",
      "Arctic and Tropical Weather Hazards",
      "Aviation Routine Weather Report (METAR)",
      "The Terminal Aerodrome Forecast (TAF)",
      "Enroute Forecasts",
      "Surface Analysis and Constant Pressure Charts",
      "Reports and Forecasts of Hazardous Weather",
      "PIREPs",
    ],
  },

  /* ─── PHAK — Pilot's Handbook of Aeronautical Knowledge ───────── */
  PHAK: {
    2: [
      "History of ADM",
      "Risk Management",
      "Human Factors",
      "Single-Pilot Resource Management (SRM)",
      "Use of Resources",
      "Situational Awareness",
      "Workload Management",
      "Automation",
    ],
    3: [
      "Aircraft Design, Certification, and Airworthiness",
      "Lift and Basic Aerodynamics",
      "Major Components",
      "Types of Aircraft Construction",
      "Instrumentation: Moving into the Future",
    ],
    4: ["Structure of the Atmosphere", "Theories in the Production of Lift", "Airfoil Design"],
    5: [
      "Forces Acting on the Aircraft",
      "Wingtip Vortices",
      "Ground Effect",
      "Axes of an Aircraft",
      "Moment and Moment Arm",
      "Aircraft Design Characteristics",
      "Aerodynamic Forces in Flight Maneuvers",
      "Stalls",
      "Basic Propeller Principles",
      "Load Factors",
      "Rate of Turn",
      "Radius of Turn",
      "Weight and Balance",
      "High Speed Flight",
    ],
    6: ["Flight Control Systems", "Autopilot"],
    7: ["Powerplant", "Airframe Systems"],
    8: [
      "Pitot-Static Flight Instruments",
      "Electronic Flight Display (EFD)",
      "Gyroscopic Flight Instruments",
      "Attitude and Heading Reference System (AHRS)",
      "Angle of Attack Indicators",
      "Compass Systems",
      "Outside Air Temperature (OAT) Gauge",
    ],
    9: [
      "Preliminary Pages",
      "General (Section 1)",
      "Limitations (Section 2)",
      "Emergency Procedures (Section 3)",
      "Normal Procedures (Section 4)",
      "Performance (Section 5)",
      "Weight and Balance/Equipment List (Section 6)",
      "Systems Description (Section 7)",
      "Handling, Service, and Maintenance (Section 8)",
      "Supplements (Section 9)",
      "Safety Tips (Section 10)",
      "Aircraft Documents",
      "Aircraft Maintenance",
    ],
    10: [
      "Weight Control",
      "Balance, Stability, and Center of Gravity",
      "Terms and Definitions",
      "Principles of Weight and Balance Computations",
      "Determining Loaded Weight and CG",
      "Shifting, Adding, and Removing Weight",
    ],
    11: [
      "Importance of Performance Data",
      "Structure of the Atmosphere",
      "Performance",
      "Takeoff and Landing Performance",
      "Performance Speeds",
      "Performance Charts",
      "Transport Category Aircraft Performance",
    ],
    12: [
      "Atmosphere",
      "Wind and Currents",
      "Atmospheric Stability",
      "Moisture and Temperature",
      "Air Masses",
      "Fronts",
      "Thunderstorms",
    ],
    13: [
      "Observations",
      "Service Outlets",
      "Weather Briefings",
      "Aviation Weather Reports",
      "Aviation Forecasts",
      "Weather Charts",
      "Weather Avoidance Assistance",
      "Pilot Responsibility",
    ],
    14: [
      "Airport Categories",
      "Sources for Airport Data",
      "Airport Markings and Signs",
      "Airport Lighting",
      "Wind Direction Indicators",
      "Traffic Patterns",
      "Radio Communications",
      "Air Traffic Control (ATC) Services",
      "Wake Turbulence",
      "Collision Avoidance",
      "Pilot Deviations (PDs)",
      "Runway Incursion Avoidance",
      "Engineered Materials Arresting Systems (EMAS)",
    ],
    15: [
      "Controlled Airspace",
      "Uncontrolled Airspace",
      "Special Use Airspace",
      "Other Airspace Areas",
      "Air Traffic Control and the National Airspace System",
      "Special Operations",
    ],
    16: [
      "Aeronautical Charts",
      "Latitude and Longitude (Meridians and Parallels)",
      "Time Zones",
      "Measurement of Direction",
      "Effect of Wind",
      "Basic Calculations",
      "Flight Computers",
      "Pilotage",
      "Dead Reckoning",
      "Flight Planning",
      "Ground-Based Navigation",
      "Global Positioning System (GPS)",
      "Lost Procedures",
      "Flight Diversion",
    ],
    17: [
      "Obtaining a Medical Certificate",
      "Health and Physiological Factors Affecting Pilot Performance",
      "Vision in Flight",
    ],
  },

  /* ─── Jeppesen General Airway Manual — 8 bloques ─────────────── */
  JEPP: {
    1: ["Definiciones", "Abbreviations"],
    2: [
      "NAVAID Symbols",
      "NAVAID Boxes",
      "Off Chart NAVAID Depiction",
      "Crossing Altitudes in the Chart Planview",
      "Speed Restrictions in the Chart Planview",
      "Charting Symbols Legend",
      "Enroute Chart Legend",
      "SID/DP and STAR Chart Legend",
      "Airport Chart Legend",
      "Approach Chart Legend",
      "Approach Chart Legend — Airline Format",
      "Chart Legend — EASA AIR OPS (Aerodrome Operating Minimums)",
    ],
    3: [
      "Signs and Markings (generalidades)",
      "United States Airport Sign Systems",
      "United States Instrument Runway Markings",
      "ICAO Recommended Airport Signs, Runway and Taxiway Markings",
    ],
    4: [
      "Frequency Bands",
      "Frequency Allocation",
      "Airborne Stations",
      "Air Traffic Control Operations (estaciones al servicio del ATC)",
      "Effective Range of Radio Transmission",
      "Navigation Aids — panorama general (clasificación y uso)",
      "Navigation Aids — características y operación (Section 1)",
    ],
    5: [
      "General Requirements",
      "Departure Procedures",
      "En-route Procedures",
      "Arrival Procedures",
      "Approach Procedures",
      "Holding Procedures",
      "Altimeter Setting Procedures",
      "SSR Transponder Operating Procedures",
      "Noise Abatement Procedures",
      "Operational Flight Information",
      "Mach Number Technique",
    ],
    6: [
      "Annex 2 — Rules of the Air",
      "Annex 11 — Air Traffic Services",
      "Annex 10 — Aeronautical Telecommunications",
      "Air Traffic Management (Doc 4444)",
      "Appendix 2 — Flight Plan",
      "Appendix 1 — Air-Reporting by Voice Communications",
      "Appendix 4 — Air Traffic Incident Report",
    ],
    7: [
      "Performance-Based Navigation (PBN) y RNAV",
      "Surveillance Systems",
      "PBCS (Doc 9869)",
      "CPDLC",
    ],
    8: [
      "Procedimientos de emergencia: generalidades y prioridad",
      "Frecuencias de socorro",
      "Transpondedor en emergencia",
      "Señales de socorro y urgencia",
      "Interferencia ilícita",
      "Descenso de emergencia",
      "Radiotelefonía de socorro y urgencia (MAYDAY / PAN PAN)",
      "Falla de comunicaciones",
      "Interceptación",
      "Búsqueda y salvamento (SAR)",
      "Gestión de combustible en vuelo (MINIMUM FUEL / MAYDAY FUEL)",
    ],
  },

  /* ─── Legislación — un capítulo por ordenamiento ──────────────── */
  LEG: {
    1: ["Artículo 32"],
    2: [
      "Convenio de Chicago",
      "Anexos OACI",
      "Convenio de Varsovia",
      "Convenio de Montreal de 1999",
      "Convenio de Tokio",
      "Convenio de La Haya",
      "Convenio de Montreal de 1971",
    ],
    3: [
      "Disposiciones generales (art. 3)",
      "Autoridad de aviación civil (art. 7)",
      "Servicio de transporte aéreo (art. 17 Bis)",
      "Operaciones (arts. 32 a 34)",
      "Tránsito aéreo (arts. 35 a 37)",
      "Personal técnico aeronáutico (art. 38)",
      "Comandante de la aeronave (arts. 40 a 41)",
      "Daños a terceros (arts. 70 a 71)",
      "Accidentes y búsqueda y salvamento (arts. 79 a 82)",
      "Sanciones (arts. 88 a 90)",
    ],
    4: [
      "Medidas de seguridad para prevenir actos de interferencia ilícita (arts. 43 a 47)",
      "Personal de vuelo (arts. 77 a 86)",
      "Disposiciones generales para la operación (arts. 103 a 105)",
      "Operaciones de vuelo (arts. 111 a 120)",
      "Instrumentos, equipo y documentos de vuelo (art. 131)",
      "Servicios a la navegación aérea (arts. 158 a 162)",
      "Reglas del aire (arts. 168 a 174)",
      "Búsqueda, salvamento e investigación de accidentes (arts. 175 a 187)",
      "Sanciones (arts. 196 a 197)",
    ],
    5: [
      "Clasificación de aeródromos (art. 6)",
      "Operaciones (arts. 104 a 115)",
      "Control de acceso (art. 156)",
      "Autoridad aeroportuaria (art. 169)",
    ],
    6: ["Evaluación médica al personal técnico-aeronáutico y aspirantes (arts. 13 a 17)"],
    7: [
      "Control de aduana en el despacho (art. 20)",
      "Contribuciones, cuotas compensatorias y demás regulaciones al comercio exterior (art. 53)",
      "Afectación de mercancías y exenciones (art. 61)",
    ],
    8: ["Tráfico aéreo (art. 31)", "Equipajes y menajes (art. 98)"],
    9: [
      "Jornada de trabajo (arts. 60 a 67)",
      "Trabajo de las tripulaciones aeronáuticas (arts. 215 a 245)",
    ],
    10: [
      "Circular Obligatoria de Revalidación de Licencia CO AV-12.1/07 R5",
      "Circular Obligatoria de Artículos Prohibidos CO SA-17.2/10 R3",
    ],
  },

  /* ─── OACI Anexo 10, Volumen II ───────────────────────────────── */
  // El temario lista los capítulos del Anexo sin desglose de secciones.
  ANX10: {},
};

/** Secciones del temario para un capítulo concreto (vacío si no hay). */
export function seccionesDe(
  fuente: string | undefined,
  capitulo: number | undefined,
): readonly string[] {
  if (!fuente || capitulo === undefined || capitulo === null) return [];
  return TEMARIO_SECCIONES[fuente]?.[capitulo] ?? [];
}

/** true si la sección es una de las del temario para ese capítulo. */
export function esSeccionDelTemario(fuente: string, capitulo: number, seccion: string): boolean {
  return seccionesDe(fuente, capitulo).includes(seccion);
}
