/**
 * Biblioteca real de FlightPath: los 104 libros/manuales oficiales de la carpeta
 * "libros" de Google Drive del cliente (PDFs compartidos con enlace público).
 * Cada entrada apunta al visor embebible de Drive (/preview); la descarga se
 * deriva del mismo ID. Clasificados por materia CIAAC.
 */

export interface LibroSeed {
  id: string;
  titulo: string;
  autor: string;
  materia: string; // slug CIAAC o "" (general)
  tags: string[];
  badge: string;
  badgeColor: string;
  emoji: string; // FPIconName
  gradient: string;
  fileUrl: string;
  descargable: boolean;
  imprimible: boolean;
  muestraGratis: boolean;
  status: "publicada" | "oculta";
}

export const LIBROS_SEED: LibroSeed[] = [
  {
    id: "aero-avanzada",
    titulo: "Aerodinámica Avanzada (L3) — Piloto Aviador Comercial",
    autor: "CIAAC",
    materia: "aerodinamica",
    tags: ["oficial", "aerodinamica"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "plane",
    gradient: "linear-gradient(135deg,#667eea,#764ba2)",
    fileUrl: "https://drive.google.com/file/d/18fGcKp1lWJI-2IZRs23ZputfWObXnRU8/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "aero-basica",
    titulo: "Aerodinámica Básica",
    autor: "CIAAC",
    materia: "aerodinamica",
    tags: ["oficial", "aerodinamica"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "plane",
    gradient: "linear-gradient(135deg,#667eea,#764ba2)",
    fileUrl: "https://drive.google.com/file/d/1SJTfPZZn11pV81zJnpOKnuW5FhIquAR_/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_007",
    titulo: "Aerodinámica y Actuaciones del Avión",
    autor: "Aníbal Isidoro Carmona",
    materia: "aerodinamica",
    tags: ["libro", "aerodinamica"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "plane",
    gradient: "linear-gradient(135deg,#667eea,#764ba2)",
    fileUrl: "https://drive.google.com/file/d/1DUJpItjvZixRc_ksrc2Q6nm5kXuhBobS/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_002",
    titulo: "Aerodynamics of the Helicopter",
    autor: "Alfred Gessow y Garry C. Myers",
    materia: "aerodinamica",
    tags: ["libro", "aerodinamica"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "plane",
    gradient: "linear-gradient(135deg,#667eea,#764ba2)",
    fileUrl: "https://drive.google.com/file/d/10CowOy2f_rTo2cg2Kmb2d5IW4ZWbJtuY/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_090",
    titulo: "Principles of Helicopter Aerodynamics (2ª ed.)",
    autor: "J. Gordon Leishman",
    materia: "aerodinamica",
    tags: ["libro", "aerodinamica"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "plane",
    gradient: "linear-gradient(135deg,#667eea,#764ba2)",
    fileUrl: "https://drive.google.com/file/d/1X3Qovj0W9BWfow4rt5qyLZaZZcArmXOQ/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_079",
    titulo: "The Foundations of Helicopter Flight",
    autor: "Simon Newman",
    materia: "aerodinamica",
    tags: ["libro", "aerodinamica"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "plane",
    gradient: "linear-gradient(135deg,#667eea,#764ba2)",
    fileUrl: "https://drive.google.com/file/d/1VmLitQg8hr48z4DnpXsEihIGPSPKuRMV/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_009",
    titulo: "Aeronaves y Motores: Generalidades",
    autor: "CIAAC",
    materia: "aeronaves-motores",
    tags: ["oficial", "aeronaves-motores"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "settings",
    gradient: "linear-gradient(135deg,#43e97b,#38f9d7)",
    fileUrl: "https://drive.google.com/file/d/12jqV6r4HpSxoj50TZJ9dPD572Y4EppMu/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_077",
    titulo: "Motores de Combustión Interna",
    autor: "Varios autores",
    materia: "aeronaves-motores",
    tags: ["libro", "aeronaves-motores"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "settings",
    gradient: "linear-gradient(135deg,#43e97b,#38f9d7)",
    fileUrl: "https://drive.google.com/file/d/1Rgt7QC_LfWyhK_6lzCEGxR7og1GIyPEu/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_021",
    titulo: "Anexo 14 — Aeródromos, Vol. I: Diseño y Operaciones de Aeródromos",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1aGL3j4qNkYF72dBwQfvBlaaZ_C7uCqjL/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_022",
    titulo: "Anexo 14 — Aeródromos, Vol. II: Helipuertos",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1ghH_EAGbtFs-m3BRsYKvHSBKXkR3b8Mu/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_024",
    titulo: "Anexo 16 — Protección del Medio Ambiente, Vol. I: Ruido de las Aeronaves",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1XVR0fmCUU-7a90UBxXlC7I01iMJ6MlP4/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_025",
    titulo: "Anexo 16 — Protección del Medio Ambiente, Vol. II: Emisiones de los Motores",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1h-2C1f12GzTY6NTkS5jAwlvA1BxgnhGD/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_029",
    titulo: "Anexo 2 — Reglamento del Aire",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1rhVYv3pkdz_jbvw1jtz1-SYxuzBs_7ib/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_033",
    titulo: "Anexo 7 — Marcas de Nacionalidad y de Matrícula de las Aeronaves",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1bEnmWFwAaHuLc6TwsGuKxloVr5_RV-H4/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_087",
    titulo: "Anexo 9 al Convenio sobre Aviación Civil — Facilitación (ed. 2022)",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1ShZ4fnCopnQAxQMVKGCXa5UMxMcW2EPI/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_034",
    titulo: "Anexo 9 — Facilitación",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1HDGRtVpS49I8Gf4Kr18jxji1H5sfaE_4/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_045",
    titulo: "Constitución Política de los Estados Unidos Mexicanos",
    autor: "Cámara de Diputados",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1lhH2SxyXeaVqF7xUXyQ2_G9L0JRi3fho/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_063",
    titulo: "Ley de Aeropuertos",
    autor: "Cámara de Diputados",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/14TPp-Cg4o-Y2MQki_VKD9EmJFyh2hsVy/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_064",
    titulo: "Ley de Aviación Civil",
    autor: "Cámara de Diputados",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1NfFMFpYmJCWlreoa9PVCAuThxm8UM1U-/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_065",
    titulo: "Ley Federal del Trabajo",
    autor: "Cámara de Diputados",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1VYQHhDEPFkuhbOjO_OmbUzLFeyKA-btV/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_066",
    titulo: "Ley Reglamentaria del Artículo 5º Constitucional (Ejercicio de las Profesiones)",
    autor: "Cámara de Diputados",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1wNiDH5eqCeuVq7NkkgoF0eV0mhnaPgc5/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_071",
    titulo: "Marcas de Nacionalidad y de Matrícula de las Aeronaves",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1ZtRn1-0Zuu_0Lp2b_xw2aKg_z3mERcG1/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_097",
    titulo: "NOM-018-SCT3-2012 — Contenido del Manual de Vuelo",
    autor: "SCT — Diario Oficial de la Federación",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1kbd0Xq3B94C2YCrqP3GIz07OBq-m7aIH/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_099",
    titulo: "NOM-020/2-SCT3-2013 — Reglas del Aire para la Operación de las Aeronaves",
    autor: "SCT — Diario Oficial de la Federación",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/12RXiaLXxJviXuJuiW0w48dzPKCtTnVGe/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_094",
    titulo: "Reglamento de la Ley de Aviación Civil",
    autor: "Cámara de Diputados",
    materia: "legislacion",
    tags: ["ley", "legislacion"],
    badge: "Ley",
    badgeColor: "#8A1538",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1ze6wNAJmKEsBTgjQYblPQc2QVQGKAxqp/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_095",
    titulo: "Reglamento del Aire",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/19Crz2Y2rASp_230nB9TC5jm83ZweGmKW/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_086",
    titulo: "Suplemento al Anexo 9 — Facilitación",
    autor: "OACI",
    materia: "legislacion",
    tags: ["oaci", "legislacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "scale",
    gradient: "linear-gradient(135deg,#f2994a,#f2c94c)",
    fileUrl: "https://drive.google.com/file/d/1q9rn2qlcS98_VDB8xEhyp3_WO1UOJA2J/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_011",
    titulo: "Anatomía y Fisiología del Cuerpo Humano",
    autor: "Varios autores",
    materia: "medicina",
    tags: ["libro", "medicina"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "stethoscope",
    gradient: "linear-gradient(135deg,#fa709a,#fee140)",
    fileUrl: "https://drive.google.com/file/d/1E8cWmt1E-YA3fagVTbP1i0f1_0I3buMU/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_069",
    titulo: "Manual de Medicina Aeronáutica Civil",
    autor: "OACI",
    materia: "medicina",
    tags: ["oaci", "medicina"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "stethoscope",
    gradient: "linear-gradient(135deg,#fa709a,#fee140)",
    fileUrl: "https://drive.google.com/file/d/1y8S3HIvBK_mUByrZZ2bvpzWYm_mEL35u/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_003",
    titulo: "Manual de Medicina Aeronáutica Civil (Doc 8984)",
    autor: "OACI",
    materia: "medicina",
    tags: ["oaci", "medicina"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "stethoscope",
    gradient: "linear-gradient(135deg,#fa709a,#fee140)",
    fileUrl: "https://drive.google.com/file/d/1tCCRFu8fkOVHgZbFO19WmRBWQkqahBH2/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_073",
    titulo: "Medicina Aeronáutica",
    autor: "CIAAC",
    materia: "medicina",
    tags: ["oficial", "medicina"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "stethoscope",
    gradient: "linear-gradient(135deg,#fa709a,#fee140)",
    fileUrl: "https://drive.google.com/file/d/11CJ5qW0DYqibmeEb632xysM_OJPtzcKO/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_072",
    titulo: "Medicina Aeronáutica para el Médico de Familia",
    autor: "Varios autores",
    materia: "medicina",
    tags: ["libro", "medicina"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "stethoscope",
    gradient: "linear-gradient(135deg,#fa709a,#fee140)",
    fileUrl: "https://docs.google.com/document/d/14pbOhPyFPyNyzxoe4EuOc1_fnCr4WV_IljglZrXK5Uk/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_030",
    titulo: "Anexo 3 — Servicio Meteorológico para la Navegación Aérea Internacional",
    autor: "OACI",
    materia: "meteorologia",
    tags: ["oaci", "meteorologia"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/1uDeC56A8VDxQywtPjKUpBfVVg9no3jUx/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_035",
    titulo: "Aviation Weather (AC 00-6A)",
    autor: "Federal Aviation Administration",
    materia: "meteorologia",
    tags: ["faa", "meteorologia"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/11vr0EqCfJLjH_xslbLaJEGLHbKifMvMQ/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_056",
    titulo: "Interpretación de los Informes Aeronáuticos de Observaciones de Superficie",
    autor: "CIAAC",
    materia: "meteorologia",
    tags: ["oficial", "meteorologia"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/1VkfknGj7dFwlwJv3tNfqu05IHMAH6sP_/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_059",
    titulo: "Jeppesen Aviation Weather",
    autor: "Jeppesen",
    materia: "meteorologia",
    tags: ["jeppesen", "meteorologia"],
    badge: "Jeppesen",
    badgeColor: "#6C0820",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/1kc1sEirzme2TCp-5UcY3x6D4qbNd3M_s/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_075",
    titulo: "Meteorología 1",
    autor: "Escuela de Aviación Meteoro",
    materia: "meteorologia",
    tags: ["libro", "meteorologia"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/1hx1rPiIzdni3X7RN1VMkmG1Mg9eX27y-/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_074",
    titulo: "Meteorología General",
    autor: "CIAAC",
    materia: "meteorologia",
    tags: ["oficial", "meteorologia"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/119sOYOM5_lYnXczkcM-aDyCzInCRDlHk/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_076",
    titulo: "Métodos para la Preparación de Mapas y Diagramas Meteorológicos",
    autor: "OMM",
    materia: "meteorologia",
    tags: ["libro", "meteorologia"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/1FuwMh_qbTePJsFDqZdBf4ACO3FoTUBd2/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_096",
    titulo: "Riesgos Atmosféricos para la Aeronáutica",
    autor: "CIAAC",
    materia: "meteorologia",
    tags: ["oficial", "meteorologia"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "cloud",
    gradient: "linear-gradient(135deg,#4facfe,#00f2fe)",
    fileUrl: "https://drive.google.com/file/d/1Ze_1Ro2Zmtg72943dy4ZsGF3KUCyWzRm/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_055",
    titulo: "Instrument Procedures Handbook (FAA-H-8261-1A)",
    autor: "Federal Aviation Administration",
    materia: "navegacion",
    tags: ["faa", "navegacion"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "map",
    gradient: "linear-gradient(135deg,#a18cd1,#fbc2eb)",
    fileUrl: "https://drive.google.com/file/d/11YB7lXHWJQyuMFO8eK9qNQyTmuPhk7Yr/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_058",
    titulo: "IX-2 Navegación Aérea Avanzada",
    autor: "CIAAC",
    materia: "navegacion",
    tags: ["oficial", "navegacion"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "map",
    gradient: "linear-gradient(135deg,#a18cd1,#fbc2eb)",
    fileUrl: "https://drive.google.com/file/d/1SxR4fZEifH5DX_XvQotI9zn7afXhHD4V/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_088",
    titulo: "Procedimientos para los Servicios de Navegación Aérea",
    autor: "OACI",
    materia: "navegacion",
    tags: ["oaci", "navegacion"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "map",
    gradient: "linear-gradient(135deg,#a18cd1,#fbc2eb)",
    fileUrl: "https://drive.google.com/file/d/1-NQw3DmymnZCHXqQlkc4bOxs8g7ZiEmP/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_018",
    titulo: "Anexo 11 — Servicios de Tránsito Aéreo",
    autor: "OACI",
    materia: "servicios-transito",
    tags: ["oaci", "servicios-transito"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1-9f250zm1iphCSrbH0HaaD6EAN2dxp6z/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_019",
    titulo: "Anexo 12 — Búsqueda y Salvamento",
    autor: "OACI",
    materia: "servicios-transito",
    tags: ["oaci", "servicios-transito"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1tTmaP7b4nmxzIauE2cPbleV3ec6RIHic/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_038",
    titulo: "Climb Via / Descend Via Speed Clearances — Preguntas Frecuentes",
    autor: "Federal Aviation Administration",
    materia: "servicios-transito",
    tags: ["faa", "servicios-transito"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1CsWH9hyjCg_RvwfLL3tDS73Befki70-O/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_046",
    titulo: "Doc 4444 — Gestión del Tránsito Aéreo (PANS-ATM)",
    autor: "OACI",
    materia: "servicios-transito",
    tags: ["oaci", "servicios-transito"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/18XBXzU57BfEsgPUsJK9iw4reVrggTMUG/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_098",
    titulo: "Manual de Gestión de Tránsito Aéreo de México",
    autor: "SENEAM",
    materia: "servicios-transito",
    tags: ["oficial", "servicios-transito"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1qHvHUmhTQ4yzuSZnz1TrXXzFr9W3MAJb/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_100",
    titulo: "Manual de Gestión de Tránsito Aéreo de México (SENEAM)",
    autor: "SENEAM",
    materia: "servicios-transito",
    tags: ["oficial", "servicios-transito"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1XGR-R81ye3hvxv9VARtSyQ9uoxQbwGK9/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "oculta",
  },
  {
    id: "lib_101",
    titulo: "Servicios de Tránsito Aéreo",
    autor: "CIAAC",
    materia: "servicios-transito",
    tags: ["oficial", "servicios-transito"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "tower",
    gradient: "linear-gradient(135deg,#30cfd0,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1e7-jWd0H3JgwGsJLnUqLsj0a6xaKzC53/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_017",
    titulo: "Anexo 10 al Convenio sobre Aviación Civil — Telecomunicaciones Aeronáuticas",
    autor: "OACI",
    materia: "comunicaciones",
    tags: ["oaci", "comunicaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1UeLpDeyaZEu8fXbYRVlqJtfh3SgV3ckB/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_012",
    titulo: "Anexo 10 — Telecomunicaciones Aeronáuticas, Vol. I: Radioayudas para la Navegación",
    autor: "OACI",
    materia: "comunicaciones",
    tags: ["oaci", "comunicaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/10aWJ9o1czjrBRNaCRHiKeBJKUIu5MFxW/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_013",
    titulo: "Anexo 10 — Telecomunicaciones Aeronáuticas, Vol. II: Procedimientos de Comunicaciones",
    autor: "OACI",
    materia: "comunicaciones",
    tags: ["oaci", "comunicaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1LF-Ys_kFnB0rFejOTHDfejXpTFPcXMJy/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_014",
    titulo: "Anexo 10 — Telecomunicaciones Aeronáuticas, Vol. III: Sistemas de Comunicaciones",
    autor: "OACI",
    materia: "comunicaciones",
    tags: ["oaci", "comunicaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1qOvRb7yRlmP78Qak4EyffHjuoxFHO7S9/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_015",
    titulo: "Anexo 10 — Telecomunicaciones Aeronáuticas, Vol. IV: Sistemas de Vigilancia y Anticolisión",
    autor: "OACI",
    materia: "comunicaciones",
    tags: ["oaci", "comunicaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1BjBzPtO6KLVcqXST58Ymgzn8mPHH2fJA/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_016",
    titulo: "Anexo 10 — Telecomunicaciones Aeronáuticas, Vol. V: Utilización del Espectro de Radiofrecuencias",
    autor: "OACI",
    materia: "comunicaciones",
    tags: ["oaci", "comunicaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/17Pbg0L2c-XxmmgnEipCYuNrIOLj-GTAU/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_037",
    titulo: "Capítulo 12.2 — Procedimientos de Comunicación",
    autor: "AFAC",
    materia: "comunicaciones",
    tags: ["oficial", "comunicaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/139Wq4LlYvUcJNNSfq5P1xRvNq0P3yEtp/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_041",
    titulo: "CO AV-21.02/10 R1 — Reglas de Tránsito Aéreo y Procedimientos de Comunicaciones (PANS)",
    autor: "DGAC",
    materia: "comunicaciones",
    tags: ["oficial", "comunicaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1Ob5ZQxBtA2nIaVfA8yDZDznl3r-myimy/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_042",
    titulo: "CO AV-26/11 R3 — Utilización de la Fraseología Aeronáutica",
    autor: "DGAC",
    materia: "comunicaciones",
    tags: ["oficial", "comunicaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1G5lU0lv-PpS1zZqKW7via18rinRvqG8R/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_057",
    titulo: "IV-3 AEROCOM — Comunicaciones Aeronáuticas",
    autor: "CIAAC",
    materia: "comunicaciones",
    tags: ["oficial", "comunicaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1OWbvQvZZ1AiSCRO6jm4GRJ7BJTq9Cf_8/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_093",
    titulo: "RAC 10 — Requisitos para los Servicios de Telecomunicaciones Aeronáuticas",
    autor: "AFAC",
    materia: "comunicaciones",
    tags: ["oficial", "comunicaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/10eUbUkkdb2p0cekFogP9vLDX2oviFZ7w/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_103",
    titulo: "Reglamento de Radiocomunicaciones (Vol. 1)",
    autor: "UIT",
    materia: "comunicaciones",
    tags: ["libro", "comunicaciones"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/169UzNPmLq9H-2ufaZ9z_5YEHhn-FegDR/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_053",
    titulo: "Términos y Definiciones del Cuadro Nacional de Atribución de Frecuencias (CNAF)",
    autor: "IFT",
    materia: "comunicaciones",
    tags: ["oficial", "comunicaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "radio",
    gradient: "linear-gradient(135deg,#5ee7df,#b490ca)",
    fileUrl: "https://drive.google.com/file/d/1HQ1GfgeVGTxOdWTktCCxCPKEYZzVEjm_/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_008",
    titulo: "Aeronautical Information Manual (AIM)",
    autor: "Federal Aviation Administration",
    materia: "manuales-ais",
    tags: ["faa", "manuales-ais"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "book",
    gradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
    fileUrl: "https://drive.google.com/file/d/1hAUZp_bvP91wdTnarG7Jjbj9xckRngtk/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_023",
    titulo: "Anexo 15 — Servicios de Información Aeronáutica",
    autor: "OACI",
    materia: "manuales-ais",
    tags: ["oaci", "manuales-ais"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "book",
    gradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
    fileUrl: "https://drive.google.com/file/d/1D48wHb63ZG9FohbjikbaCyH8_dGlChoD/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_060",
    titulo: "Jeppesen General Airway Manual",
    autor: "Jeppesen",
    materia: "manuales-ais",
    tags: ["jeppesen", "manuales-ais"],
    badge: "Jeppesen",
    badgeColor: "#6C0820",
    emoji: "book",
    gradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
    fileUrl: "https://drive.google.com/file/d/1XP-SzUEFmEC8fQHCeW1wl8-OOOygPdYU/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_061",
    titulo: "Jeppesen — Cartas Todo México",
    autor: "Jeppesen",
    materia: "manuales-ais",
    tags: ["jeppesen", "manuales-ais"],
    badge: "Jeppesen",
    badgeColor: "#6C0820",
    emoji: "book",
    gradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
    fileUrl: "https://drive.google.com/file/d/1PLFJqkhNwj9fH0eNLvEcv1wbWWWWb9KM/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_102",
    titulo: "Simbología y Definiciones",
    autor: "CIAAC",
    materia: "manuales-ais",
    tags: ["oficial", "manuales-ais"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "book",
    gradient: "linear-gradient(135deg,#ffecd2,#fcb69f)",
    fileUrl: "https://drive.google.com/file/d/1fNmCDjYBl8C11etQNz8pjGizHQbjQxRq/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_039",
    titulo: "CO AV-09.6/07 R1 — Factores Humanos en la Aviación",
    autor: "DGAC",
    materia: "factores-humanos",
    tags: ["oficial", "factores-humanos"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1vHQJth3SogncrfurskwDg6nJB3nzr4AS/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_085",
    titulo: "Compendio sobre Factores Humanos Núm. 15",
    autor: "OACI",
    materia: "factores-humanos",
    tags: ["oaci", "factores-humanos"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1Lt0kvYDo5z9BrM1P8XORI8fMKIHoR5NQ/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_049",
    titulo: "Factores Humanos en Aviación — Tema 8",
    autor: "CIAAC",
    materia: "factores-humanos",
    tags: ["oficial", "factores-humanos"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1N6RnzTL21hknFtgtdwLCOZFsrt3MHzve/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_050",
    titulo: "Factores Humanos en Aviación — Tema 8 (Dr. Octavio Amezcua)",
    autor: "Dr. Octavio Amezcua — CIAAC",
    materia: "factores-humanos",
    tags: ["oficial", "factores-humanos"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/17soB0eTZb8ofe6qE-zBaa8_hBAV5Ee_y/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_083",
    titulo: "Los Factores Humanos en las Operaciones",
    autor: "OACI",
    materia: "factores-humanos",
    tags: ["oaci", "factores-humanos"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1iKBNiT9eus49Dug7cpTrk4jHakH2rz9p/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_067",
    titulo: "Manual de Factores Humanos para la Aviación de Estado (MAFAH)",
    autor: "Fuerza Aérea Mexicana",
    materia: "factores-humanos",
    tags: ["oficial", "factores-humanos"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1644JrragGUt5jcZBrhHCBif9nU793H3F/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_082",
    titulo: "Manual de Instrucción sobre Factores Humanos (Doc 9683)",
    autor: "OACI",
    materia: "factores-humanos",
    tags: ["oaci", "factores-humanos"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1Ybapmo1vYSC5Kqnj9ucB6RBk4oa00aln/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_051",
    titulo: "Manual on Human Performance for Regulators",
    autor: "OACI",
    materia: "factores-humanos",
    tags: ["oaci", "factores-humanos"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1S6j-tFvlyjTV7ttvcuDfK6VPmu1DGHkN/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_092",
    titulo: "Psicología y Factores Humanos de la Aviación",
    autor: "Varios autores",
    materia: "factores-humanos",
    tags: ["libro", "factores-humanos"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1QFi1mYA2DvXPuq5JV9yqYVJmFwg_Io-T/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_052",
    titulo: "Starter Pack — Factores Humanos y Desempeño Humano",
    autor: "OACI",
    materia: "factores-humanos",
    tags: ["oaci", "factores-humanos"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1CYqsrUbVaA9aK9NLECvin0Ta1peqJXwO/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
  {
    id: "lib_104",
    titulo: "Visual Illusions Awareness",
    autor: "Federal Aviation Administration",
    materia: "factores-humanos",
    tags: ["faa", "factores-humanos"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "brain",
    gradient: "linear-gradient(135deg,#2af598,#009efd)",
    fileUrl: "https://drive.google.com/file/d/1GzXK4U6chyoZ2DIeExCZpCB0Yy9avoJe/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_020",
    titulo: "Anexo 13 — Investigación de Accidentes e Incidentes de Aviación",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1qCgUPjdlSHfTKl7kbpgIq-aGA-XUlgbL/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_026",
    titulo: "Anexo 17 — Seguridad: Protección de la Aviación Civil contra Actos de Interferencia Ilícita",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1e8UgMYZBQvIDDbN42IJhrg1sEyZYhZ03/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_028",
    titulo: "Anexo 19 — Gestión de la Seguridad Operacional",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/16O4ZrfDkBi1kwQzupYc9stikpQA0W_ew/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_036",
    titulo: "CA SA-064-10 R1 — Sistema de Gestión de Seguridad Operacional (SMS)",
    autor: "DGAC",
    materia: "seguridad-aerea",
    tags: ["oficial", "seguridad-aerea"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1mMYtHC3f0bF8veMBlxBowtaP_VTpWp1b/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_044",
    titulo: "CO SA-17.2/10 R3 — Artículos Prohibidos en Aeronaves de Servicio al Público",
    autor: "DGAC",
    materia: "seguridad-aerea",
    tags: ["oficial", "seguridad-aerea"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1hAGtrp4ckxH0JBam8YOB3jg5He3zyzQH/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_068",
    titulo: "Manual de Gestión de la Seguridad Operacional",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1BQipqnF5DajaZRxxwmxv8h-EsiVS863C/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_004",
    titulo: "Manual de Gestión de la Seguridad Operacional (Doc 9859)",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1x6_ceH3cqFrTUZEmyA9YRTKsX_tlIN2E/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_070",
    titulo: "Manual de Seguridad Operacional",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1B1VaXMpVdNwsBvGf5b4LWu_PXZWCPji3/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_084",
    titulo: "Manual de Seguridad para la Protección de la Aviación Civil",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1wiOey9m7d1fVrk96Rlj_auBOg_zVHfxw/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_078",
    titulo: "Manual del Programa Estatal de Seguridad Operacional (MSSP)",
    autor: "AFAC",
    materia: "seguridad-aerea",
    tags: ["oficial", "seguridad-aerea"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/1aPK0bplunchkJUq99PydEHPVRVXNLKPW/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_091",
    titulo: "Protección de la Aviación Civil contra los Actos de Interferencia Ilícita",
    autor: "OACI",
    materia: "seguridad-aerea",
    tags: ["oaci", "seguridad-aerea"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "shield",
    gradient: "linear-gradient(135deg,#ff758c,#ff7eb3)",
    fileUrl: "https://drive.google.com/file/d/11btLI3laDQ560DpSSKRsstLzdbblq6rw/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_027",
    titulo: "Anexo 18 — Transporte sin Riesgos de Mercancías Peligrosas por Vía Aérea",
    autor: "OACI",
    materia: "operaciones",
    tags: ["oaci", "operaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1p0ocw4FOQFSWnfONSa-ZcL0twNxiZq_F/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_031",
    titulo: "Anexo 6 — Operación de Aeronaves, Parte I: Transporte Aéreo Comercial Internacional",
    autor: "OACI",
    materia: "operaciones",
    tags: ["oaci", "operaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1d4U0oRheaqYavCS4DtwJ0opEvAz1O_8x/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_032",
    titulo: "Anexo 6 — Operación de Aeronaves, Parte II: Aviación General Internacional",
    autor: "OACI",
    materia: "operaciones",
    tags: ["oaci", "operaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1IFG-7XnibnLqhomibnaO6nDnjdQ9hRHg/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_040",
    titulo: "CO AV-17.5/07 R2 — Transporte sin Riesgos de Mercancías Peligrosas por Vía Aérea",
    autor: "DGAC",
    materia: "operaciones",
    tags: ["oficial", "operaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1wESVvx71-50akbHZShY6XzNknTjS7TYT/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_043",
    titulo: "CO AV-50/07 R3 — Reglas Técnicas para Operaciones de Aeronaves de Ala Rotativa",
    autor: "DGAC",
    materia: "operaciones",
    tags: ["oficial", "operaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/14ykt5KbHqOOG3Xap1UGeg81_Yl0UF5YU/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_047",
    titulo: "Everything Explained for the Professional Pilot (Parte 1)",
    autor: "Richie Lengel",
    materia: "operaciones",
    tags: ["libro", "operaciones"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1ZAkGOIpaT7OLFlcsByYZVWVajUbYo-1f/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_048",
    titulo: "Everything Explained for the Professional Pilot (Parte 2)",
    autor: "Richie Lengel",
    materia: "operaciones",
    tags: ["libro", "operaciones"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1tYuh9H6rN8lfkEypTZF8jeqoyXKVkEXz/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_080",
    titulo: "Operaciones Aéreas",
    autor: "CIAAC",
    materia: "operaciones",
    tags: ["oficial", "operaciones"],
    badge: "Oficial",
    badgeColor: "#3D5D91",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1t4RE2MmSPwoGREBtAnwuhThH3heB1Px6/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_081",
    titulo: "Operación de Aeronaves",
    autor: "OACI",
    materia: "operaciones",
    tags: ["oaci", "operaciones"],
    badge: "OACI",
    badgeColor: "#22375C",
    emoji: "doc",
    gradient: "linear-gradient(135deg,#6a11cb,#2575fc)",
    fileUrl: "https://drive.google.com/file/d/1kkzDSY1jLHkMAEh-g26HUd-tbhpDEVvs/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_005",
    titulo: "Ace the Technical Pilot Interview",
    autor: "Gary Bristow",
    materia: "",
    tags: ["libro", "general"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "book",
    gradient: "linear-gradient(135deg,#22375C,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1wshTFxshg7nOOHk3A_MmfUAWvgtmyv4G/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_001",
    titulo: "Airline Transport Pilot Test Prep (2018)",
    autor: "ASA — Test Prep",
    materia: "",
    tags: ["libro", "general"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "book",
    gradient: "linear-gradient(135deg,#22375C,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1x_BE-nE3wNp3DJ2iEqGMjcxcPxLOzuaa/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_010",
    titulo: "Airman Testing Questions & Answers",
    autor: "Federal Aviation Administration",
    materia: "",
    tags: ["faa", "general"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "book",
    gradient: "linear-gradient(135deg,#22375C,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/16Arrd15hHxsG9icCpOx8mnaZNSlW5LYw/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_054",
    titulo: "Iniciación a la Aeronáutica",
    autor: "Antonio Creus Solé",
    materia: "",
    tags: ["libro", "general"],
    badge: "Libro",
    badgeColor: "#647DA0",
    emoji: "book",
    gradient: "linear-gradient(135deg,#22375C,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1Huv0cn208KUysK-QT6o2Ky1OhRBJAImj/preview",
    descargable: false,
    imprimible: false,
    muestraGratis: false,
    status: "publicada",
  },
  {
    id: "lib_089",
    titulo: "Pilot's Handbook of Aeronautical Knowledge (FAA-H-8083-25C)",
    autor: "Federal Aviation Administration",
    materia: "",
    tags: ["faa", "general"],
    badge: "FAA",
    badgeColor: "#5A86CB",
    emoji: "book",
    gradient: "linear-gradient(135deg,#22375C,#5A86CB)",
    fileUrl: "https://drive.google.com/file/d/1Rmf_D26WRTXJXEQLKCMCieoRUU61_dHg/preview",
    descargable: true,
    imprimible: true,
    muestraGratis: true,
    status: "publicada",
  },
];
