/** Exact routes with verified native Handbook teaching documents. */
export const CIAAC_REVIEWED_AERODYNAMICS_IDS = [
  "ciaac/aerodinamica/modulo-2-leyes-fisicas-del-vuelo/leyes-de-newton-aplicadas-al-vuelo-1",
  "ciaac/aerodinamica/modulo-2-leyes-fisicas-del-vuelo/principio-de-bernoulli-2",
  "ciaac/aerodinamica/modulo-2-leyes-fisicas-del-vuelo/perfiles-aerodinamicos-introduccion-3",
  "ciaac/aerodinamica/modulo-3-fuerzas-que-actuan-sobre-la-aeronave-en-vuelo/las-cuatro-fuerzas-de-vuelo-1",
  "ciaac/aerodinamica/modulo-3-fuerzas-que-actuan-sobre-la-aeronave-en-vuelo/corrientes-sobre-un-perfil-aerodinamico-2",
  "ciaac/aerodinamica/modulo-3-fuerzas-que-actuan-sobre-la-aeronave-en-vuelo/sustentacion-y-coeficiente-de-sustentacion-cl-3",
  "ciaac/aerodinamica/modulo-3-fuerzas-que-actuan-sobre-la-aeronave-en-vuelo/resistencia-aerodinamica-y-coeficiente-de-resistencia-cd-4",
  "ciaac/aerodinamica/modulo-3-fuerzas-que-actuan-sobre-la-aeronave-en-vuelo/coeficientes-cl-y-cd-5",
  "ciaac/aerodinamica/modulo-4-mandos-de-la-aeronave/ejes-de-la-aeronave-1",
  "ciaac/aerodinamica/modulo-4-mandos-de-la-aeronave/superficies-primarias-de-mando-2",
  "ciaac/aerodinamica/modulo-4-mandos-de-la-aeronave/superficies-secundarias-3",
  "ciaac/aerodinamica/modulo-4-mandos-de-la-aeronave/compensacion-de-los-mandos-4",
  "ciaac/aerodinamica/modulo-5-perfiles-aerodinamicos/partes-de-los-perfiles-1",
  "ciaac/aerodinamica/modulo-5-perfiles-aerodinamicos/diseno-de-los-perfiles-aerodinamicos-2",
  "ciaac/aerodinamica/modulo-5-perfiles-aerodinamicos/caracteristicas-de-los-diferentes-perfiles-3",
  "ciaac/aerodinamica/modulo-6-aumento-y-modificacion-de-la-sustentacion/flaps-1",
  "ciaac/aerodinamica/modulo-6-aumento-y-modificacion-de-la-sustentacion/uso-de-flaps-en-despegue-y-aterrizaje-2",
  "ciaac/aerodinamica/modulo-6-aumento-y-modificacion-de-la-sustentacion/dispositivos-en-el-borde-de-ataque-3",
  "ciaac/aerodinamica/modulo-6-aumento-y-modificacion-de-la-sustentacion/dispositivos-anti-sustentadores-4",
  "ciaac/aerodinamica/modulo-7-estabilidad-y-control/maniobrabilidad-controlabilidad-estabilidad-y-equilibrio-1",
  "ciaac/aerodinamica/modulo-7-estabilidad-y-control/estabilidad-estatica-y-dinamica-2",
  "ciaac/aerodinamica/modulo-7-estabilidad-y-control/estabilidad-longitudinal-lateral-y-direccional-3",
  "ciaac/aerodinamica/modulo-7-estabilidad-y-control/centro-aerodinamico-centro-de-presion-y-centro-de-gravedad-4",
  "ciaac/aerodinamica/modulo-7-estabilidad-y-control/balanceo-holandes-5",
  "ciaac/aerodinamica/modulo-7-estabilidad-y-control/asimetria-de-potencias-6",
  "ciaac/aerodinamica/modulo-8-maniobras/ascenso-1",
  "ciaac/aerodinamica/modulo-8-maniobras/vuelo-recto-y-nivelado-2",
  "ciaac/aerodinamica/modulo-8-maniobras/velocidad-de-maniobra-3",
  "ciaac/aerodinamica/modulo-8-maniobras/viraje-y-angulo-de-banqueo-4",
  "ciaac/aerodinamica/modulo-8-maniobras/descenso-5",
  "ciaac/aerodinamica/modulo-8-maniobras/aterrizaje-6",
  "ciaac/aerodinamica/modulo-8-maniobras/ala-rotativa-principios-basicos-7",
] as const;
