/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuestionarioRouteImport } from './routes/cuestionario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardFlashcardsRouteImport } from './routes/dashboard/flashcards'
import { Route as DashboardClasesRouteImport } from './routes/dashboard/clases'
import { Route as DashboardBibliotecaRouteImport } from './routes/dashboard/biblioteca'
import { Route as DashboardBancoRouteImport } from './routes/dashboard/banco'
import { Route as DashboardMateriasIndexRouteImport } from './routes/dashboard/materias/index'
import { Route as DashboardMateriasSubjectIdRouteImport } from './routes/dashboard/materias/$subjectId'

const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuestionarioRoute = CuestionarioRouteImport.update({
  id: '/cuestionario',
  path: '/cuestionario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlashcardsRoute = DashboardFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClasesRoute = DashboardClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBibliotecaRoute = DashboardBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBancoRoute = DashboardBancoRouteImport.update({
  id: '/banco',
  path: '/banco',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMateriasIndexRoute = DashboardMateriasIndexRouteImport.update({
  id: '/materias/',
  path: '/materias/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMateriasSubjectIdRoute =
  DashboardMateriasSubjectIdRouteImport.update({
    id: '/materias/$subjectId',
    path: '/materias/$subjectId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuestionario': typeof CuestionarioRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/simulador': typeof SimuladorRoute
  '/dashboard/banco': typeof DashboardBancoRoute
  '/dashboard/biblioteca': typeof DashboardBibliotecaRoute
  '/dashboard/clases': typeof DashboardClasesRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/materias/$subjectId': typeof DashboardMateriasSubjectIdRoute
  '/dashboard/materias/': typeof DashboardMateriasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuestionario': typeof CuestionarioRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/simulador': typeof SimuladorRoute
  '/dashboard/banco': typeof DashboardBancoRoute
  '/dashboard/biblioteca': typeof DashboardBibliotecaRoute
  '/dashboard/clases': typeof DashboardClasesRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/materias/$subjectId': typeof DashboardMateriasSubjectIdRoute
  '/dashboard/materias': typeof DashboardMateriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuestionario': typeof CuestionarioRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/simulador': typeof SimuladorRoute
  '/dashboard/banco': typeof DashboardBancoRoute
  '/dashboard/biblioteca': typeof DashboardBibliotecaRoute
  '/dashboard/clases': typeof DashboardClasesRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/materias/$subjectId': typeof DashboardMateriasSubjectIdRoute
  '/dashboard/materias/': typeof DashboardMateriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuestionario'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/simulador'
    | '/dashboard/banco'
    | '/dashboard/biblioteca'
    | '/dashboard/clases'
    | '/dashboard/flashcards'
    | '/dashboard/'
    | '/dashboard/materias/$subjectId'
    | '/dashboard/materias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuestionario'
    | '/login'
    | '/register'
    | '/simulador'
    | '/dashboard/banco'
    | '/dashboard/biblioteca'
    | '/dashboard/clases'
    | '/dashboard/flashcards'
    | '/dashboard'
    | '/dashboard/materias/$subjectId'
    | '/dashboard/materias'
  id:
    | '__root__'
    | '/'
    | '/cuestionario'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/simulador'
    | '/dashboard/banco'
    | '/dashboard/biblioteca'
    | '/dashboard/clases'
    | '/dashboard/flashcards'
    | '/dashboard/'
    | '/dashboard/materias/$subjectId'
    | '/dashboard/materias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuestionarioRoute: typeof CuestionarioRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SimuladorRoute: typeof SimuladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuestionario': {
      id: '/cuestionario'
      path: '/cuestionario'
      fullPath: '/cuestionario'
      preLoaderRoute: typeof CuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flashcards': {
      id: '/dashboard/flashcards'
      path: '/flashcards'
      fullPath: '/dashboard/flashcards'
      preLoaderRoute: typeof DashboardFlashcardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clases': {
      id: '/dashboard/clases'
      path: '/clases'
      fullPath: '/dashboard/clases'
      preLoaderRoute: typeof DashboardClasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/biblioteca': {
      id: '/dashboard/biblioteca'
      path: '/biblioteca'
      fullPath: '/dashboard/biblioteca'
      preLoaderRoute: typeof DashboardBibliotecaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/banco': {
      id: '/dashboard/banco'
      path: '/banco'
      fullPath: '/dashboard/banco'
      preLoaderRoute: typeof DashboardBancoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/materias/': {
      id: '/dashboard/materias/'
      path: '/materias'
      fullPath: '/dashboard/materias/'
      preLoaderRoute: typeof DashboardMateriasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/materias/$subjectId': {
      id: '/dashboard/materias/$subjectId'
      path: '/materias/$subjectId'
      fullPath: '/dashboard/materias/$subjectId'
      preLoaderRoute: typeof DashboardMateriasSubjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBancoRoute: typeof DashboardBancoRoute
  DashboardBibliotecaRoute: typeof DashboardBibliotecaRoute
  DashboardClasesRoute: typeof DashboardClasesRoute
  DashboardFlashcardsRoute: typeof DashboardFlashcardsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMateriasSubjectIdRoute: typeof DashboardMateriasSubjectIdRoute
  DashboardMateriasIndexRoute: typeof DashboardMateriasIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBancoRoute: DashboardBancoRoute,
  DashboardBibliotecaRoute: DashboardBibliotecaRoute,
  DashboardClasesRoute: DashboardClasesRoute,
  DashboardFlashcardsRoute: DashboardFlashcardsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMateriasSubjectIdRoute: DashboardMateriasSubjectIdRoute,
  DashboardMateriasIndexRoute: DashboardMateriasIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuestionarioRoute: CuestionarioRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SimuladorRoute: SimuladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
